// Generated by Selenium IDE
import org.junit.Test;
        import org.junit.Before;
        import org.junit.After;
        import static org.junit.Assert.*;
        import static org.hamcrest.CoreMatchers.is;
        import static org.hamcrest.core.IsNot.not;
        import org.openqa.selenium.By;
        import org.openqa.selenium.WebDriver;
        import org.openqa.selenium.firefox.FirefoxDriver;
        import org.openqa.selenium.Dimension;
        import org.openqa.selenium.WebElement;
        import org.openqa.selenium.interactions.Actions;
        import org.openqa.selenium.support.ui.ExpectedConditions;
        import org.openqa.selenium.support.ui.WebDriverWait;
        import org.openqa.selenium.JavascriptExecutor;
        import org.openqa.selenium.Alert;
        import org.openqa.selenium.Keys;
        import java.util.HashMap;
        import java.util.List;
        import java.util.ArrayList;
        import java.util.Map;
public class Tests {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void WeryfikacjaKlasyfikacjiOsobyWWiekuOd10Do11lat() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2009");
        driver.findElement(By.id("rodzice")).click();
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Skrzat"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Skrzat"));
        driver.close();
    }
    @Test
    public void WeryfikacjaKlasyfikacjiOsobyWWiekuOd12Do13lat() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2007");
        driver.findElement(By.id("rodzice")).click();
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Mlodzik"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Mlodzik"));
        driver.close();
    }
    @Test
    public void WeryfikacjaKlasyfikacjiOsobyWWiekuOd14Do17lat() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2003");
        driver.findElement(By.id("rodzice")).click();
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Junior"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Junior"));
        driver.close();
    }
    @Test
    public void WeryfikacjaKlasyfikacjiOsobyWWiekuOd18Do64lat() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2000");
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Dorosly"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Dorosly"));
        driver.close();
    }
    @Test
    public void WeryfikacjaKlasyfikacjiOsobyWWiekuMniejNiz64lat() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-1954");
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Senior"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Senior"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiPolaDataUrodzenia() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Data urodzenia nie moze byc pusta"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiPolaImie() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputPassword3")).click();
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2000");
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("First name must be filled out"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiPolaNazwisko() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.manage().window().setSize(new Dimension(792, 824));
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2000");
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Nazwisko musi byc wypelnione"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiZawiadczeniaOdLekarzaDlaKategoriiDorosly() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2000");
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Dorosly"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Dorosly"));
        driver.close();
    }
    @Test
    public void WeryfikacjawWlidacjiZawiadczeniaOdLekarzaDlaKategoriiJunior() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2003");
        driver.findElement(By.id("rodzice")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Blad danych"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Blad danych"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiZawiadczeniaOdLekarzaDlaKategoriiMlodzik() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2007");
        driver.findElement(By.id("rodzice")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Blad danych"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Blad danych"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiZawiadczeniaOdLekarzaDlaKategoriiSenior() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-1954");
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Blad danych"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Blad danych"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiZawiadczeniaOdLekarzaDlaKategoriiSkrzat() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.manage().window().setSize(new Dimension(792, 824));
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2007");
        driver.findElement(By.id("rodzice")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Blad danych"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Blad danych"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiZgodyRodzicaDlaKategoriiJunior() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2003");
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Blad danych"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Blad danych"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiZgodyRodzicaDlaKategoriiMlodzik() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2007");
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Blad danych"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Blad danych"));
        driver.close();
    }
    @Test
    public void WeryfikacjaWalidacjiZgodyRodzicaDlaKategoriiSkrzat() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2009");
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Blad danych"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Blad danych"));
        driver.close();
    }
    @Test
    public void WeryfkacjaKlasyfikacjiOsobyWWiekuMniejNiz10lat() {
        driver.get("https://lamp.ii.us.edu.pl/~mtdyd/zawody//~mtdyd/zawody/");
        driver.findElement(By.id("inputEmail3")).click();
        driver.findElement(By.id("inputEmail3")).sendKeys("Anna");
        driver.findElement(By.id("inputPassword3")).sendKeys("Nowak");
        driver.findElement(By.id("dataU")).sendKeys("01-01-2010");
        driver.findElement(By.id("rodzice")).click();
        driver.findElement(By.id("lekarz")).click();
        driver.findElement(By.cssSelector(".btn")).click();
        assertThat(driver.switchTo().alert().getText(), is("Brak kwalifikacji"));
        assertThat(driver.findElement(By.id("returnSt")).getText(), is("Anna Nowak zostal zakwalifikowany do kategorii Brak kwalifikacji"));
        driver.close();
    }
}
